from fpdf import FPDF
from io import BytesIO


class MemorialPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'KENFUSE - Memorial', 0, 1, 'C')
        self.ln(5)
    
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')


class WillPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'KENFUSE - End of Life Planning Platform', 0, 1, 'C')
        self.ln(5)
    
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')


class PDFGenerator:
    @staticmethod
    def generate_memorial_pdf(memorial_data):
        """Generate a PDF for a memorial"""
        from datetime import datetime
        
        pdf = MemorialPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)
        
        # Title
        pdf.set_font('Arial', 'B', 16)
        pdf.cell(0, 10, memorial_data.get('title', 'Memorial'), 0, 1, 'C')
        pdf.ln(10)
        
        # Name
        pdf.set_font('Arial', 'B', 14)
        pdf.cell(0, 10, f"Name: {memorial_data.get('name', 'N/A')}", 0, 1)
        pdf.ln(5)
        
        # Dates
        pdf.set_font('Arial', '', 12)
        birth_date = memorial_data.get('birth_date') or 'N/A'
        death_date = memorial_data.get('death_date') or 'N/A'
        pdf.cell(0, 10, f"Birth Date: {birth_date}", 0, 1)
        pdf.cell(0, 10, f"Death Date: {death_date}", 0, 1)
        pdf.ln(5)
        
        # Biography
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, "Biography:", 0, 1)
        pdf.set_font('Arial', '', 12)
        biography = memorial_data.get('biography') or 'No biography available.'
        pdf.multi_cell(0, 10, biography)
        
        # Footer
        pdf.set_y(-30)
        pdf.set_font('Arial', 'I', 8)
        pdf.cell(0, 5, f"Generated by KENFUSE on {datetime.utcnow().strftime('%Y-%m-%d %H:%M')}", 0, 1, 'C')
        
        # Return PDF as bytes
        return pdf.output(dest='S').encode('latin-1')

    @staticmethod
    def generate_will_pdf(will_data, user_data=None):
        """Generate a PDF for a will"""
        from datetime import datetime
        
        pdf = WillPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)
        
        # Title
        pdf.set_font('Arial', 'B', 16)
        pdf.cell(0, 10, 'LAST WILL AND TESTAMENT', 0, 1, 'C')
        pdf.ln(5)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(10)
        
        # Testator Information
        if user_data:
            pdf.set_font('Arial', 'B', 12)
            pdf.cell(0, 10, 'TESTATOR INFORMATION', 0, 1)
            pdf.set_font('Arial', '', 11)
            pdf.cell(0, 8, f"Name: {user_data.get('first_name', '')} {user_data.get('last_name', '')}", 0, 1)
            pdf.cell(0, 8, f"Email: {user_data.get('email', 'N/A')}", 0, 1)
            pdf.ln(5)
        
        # Will Details
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, 'WILL DETAILS', 0, 1)
        pdf.set_font('Arial', '', 11)
        pdf.cell(0, 8, f"Title: {will_data.get('title', 'N/A')}", 0, 1)
        created_at = will_data.get('created_at')
        if created_at:
            pdf.cell(0, 8, f"Created: {created_at}", 0, 1)
        pdf.ln(10)
        
        # Declaration
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, 'DECLARATION', 0, 1)
        pdf.set_font('Arial', '', 11)
        testator_name = f"{user_data.get('first_name', '')} {user_data.get('last_name', '')}" if user_data else "the Testator"
        declaration = (f"I, {testator_name}, being of sound mind and memory, "
                       f"do hereby make, publish, and declare this to be my Last Will and Testament, "
                       f"hereby revoking all former Wills and Codicils by me made.")
        pdf.multi_cell(0, 8, declaration)
        pdf.ln(10)
        
        # Will Content
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, 'WILL CONTENT', 0, 1)
        pdf.set_font('Arial', '', 11)
        content = will_data.get('content') or 'No content provided.'
        pdf.multi_cell(0, 8, content)
        pdf.ln(10)
        
        # Beneficiaries
        beneficiaries = will_data.get('beneficiaries', [])
        if beneficiaries:
            pdf.set_font('Arial', 'B', 12)
            pdf.cell(0, 10, 'BENEFICIARIES', 0, 1)
            pdf.set_font('Arial', '', 11)
            for beneficiary in beneficiaries:
                name = beneficiary.get('name', 'N/A')
                relationship = beneficiary.get('relationship', 'N/A')
                share = beneficiary.get('share', 'N/A')
                pdf.cell(0, 8, f"- {name} ({relationship}): {share}", 0, 1)
            pdf.ln(10)
        
        # Signatures Page
        pdf.add_page()
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, 'SIGNATURES', 0, 1)
        pdf.ln(10)
        
        pdf.set_font('Arial', '', 11)
        pdf.cell(0, 8, 'Testator:', 0, 1)
        pdf.cell(0, 15, '_' * 50, 0, 1)
        pdf.cell(0, 8, testator_name, 0, 1)
        pdf.cell(0, 8, f"Date: _______________", 0, 1)
        pdf.ln(15)
        
        pdf.cell(0, 8, 'Witness 1:', 0, 1)
        pdf.cell(0, 15, '_' * 50, 0, 1)
        pdf.cell(0, 8, 'Name: _________________________', 0, 1)
        pdf.cell(0, 8, 'ID: ___________________________', 0, 1)
        pdf.ln(15)
        
        pdf.cell(0, 8, 'Witness 2:', 0, 1)
        pdf.cell(0, 15, '_' * 50, 0, 1)
        pdf.cell(0, 8, 'Name: _________________________', 0, 1)
        pdf.cell(0, 8, 'ID: ___________________________', 0, 1)
        
        # Footer
        pdf.set_y(-30)
        pdf.set_font('Arial', 'I', 8)
        pdf.cell(0, 5, f"Generated by KENFUSE on {datetime.utcnow().strftime('%Y-%m-%d %H:%M')}", 0, 1, 'C')
        
        # Return PDF as bytes
        return pdf.output(dest='S').encode('latin-1')