from io import BytesIO
from datetime import datetime

class SimplePDFGenerator:
    """Minimal PDF generator using basic text formatting"""
    
    @staticmethod
    def generate_will_pdf(will, user):
        """Generate simple will PDF"""
        buffer = BytesIO()
        
        # Create simple text-based PDF content
        pdf_content = f"""
        KENFUSE - End of Life Planning Platform
        =======================================
        
        LAST WILL AND TESTAMENT
        =======================
        
        Testator Information:
        ---------------------
        Name: {user.first_name} {user.last_name}
        Email: {user.email}
        Phone: {user.phone}
        
        Will Details:
        -------------
        Title: {will.title}
        Created: {will.created_at.strftime('%d %B, %Y')}
        Status: {will.status}
        Document ID: {will.id[:8].upper()}
        
        Declaration:
        ------------
        I, {user.first_name} {user.last_name}, being of sound mind and memory,
        do hereby make, publish, and declare this to be my Last Will and Testament,
        hereby revoking all former Wills and Codicils by me made.
        
        Will Content:
        -------------
        {will.content}
        
        """
        
        if will.beneficiaries:
            pdf_content += "\nBeneficiaries:\n"
            pdf_content += "--------------\n"
            for beneficiary in will.beneficiaries:
                pdf_content += f"Name: {beneficiary.get('name', 'N/A')}\n"
                pdf_content += f"Relationship: {beneficiary.get('relationship', 'N/A')}\n"
                pdf_content += f"Share: {beneficiary.get('share', 'N/A')}\n\n"
        
        pdf_content += f"""
        Signatures:
        -----------
        
        Testator's Signature:
        _____________________
        {user.first_name} {user.last_name}
        Date: _________________________
        
        Witnesses:
        
        1. _________________________
        Signature: _________________
        ID Number: ________________
        
        2. _________________________
        Signature: _________________
        ID Number: ________________
        
        =======================================
        Generated by KENFUSE on {datetime.now().strftime('%Y-%m-%d %H:%M')}
        Document ID: {will.id}
        Confidential - Do not distribute
        """
        
        # Convert to bytes
        pdf_bytes = pdf_content.encode('utf-8')
        buffer.write(pdf_bytes)
        buffer.seek(0)
        
        return buffer.getvalue()
    
    @staticmethod
    def generate_test_pdf():
        """Generate test PDF"""
        content = f"""
        KENFUSE TEST DOCUMENT
        =====================
        
        This is a test PDF document generated by KENFUSE.
        
        Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        
        PDF generation is working correctly!
        
        Features included:
        - Will creation and management
        - Memorial pages
        - Fundraising campaigns
        - Vendor marketplace
        - Secure document storage
        
        =====================
        End of document
        """
        
        return content.encode('utf-8')
