from flask import Blueprint, send_file, jsonify, make_response
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from fpdf import FPDF
import io
import os

pdf_bp = Blueprint('pdf', __name__)

# Method 1: Generate PDF using ReportLab
@pdf_bp.route('/generate-pdf', methods=['POST'])
def generate_pdf():
    try:
        # Create a byte stream buffer
        buffer = io.BytesIO()
        
        # Create PDF
        p = canvas.Canvas(buffer, pagesize=letter)
        p.drawString(100, 750, "KENFUSE Report")
        p.drawString(100, 730, "Generated PDF from Flask Backend")
        
        # Add dynamic content (you can customize this)
        from flask import request
        data = request.json
        if data and 'content' in data:
            p.drawString(100, 700, f"Content: {data['content']}")
        
        p.save()
        
        # Move to beginning of buffer
        buffer.seek(0)
        
        # Return PDF as downloadable file
        return send_file(
            buffer,
            as_attachment=True,
            download_name='kenfuse_report.pdf',
            mimetype='application/pdf'
        )
    except Exception as e:
        return jsonify({'error': str(e)}), 500

# Method 2: Generate PDF using FPDF (simpler)
@pdf_bp.route('/generate-simple-pdf')
def generate_simple_pdf():
    try:
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", size=12)
        pdf.cell(200, 10, txt="KENFUSE Simple Report", ln=1, align='C')
        pdf.cell(200, 10, txt="This is a simple PDF generated by Flask", ln=2, align='C')
        
        # Save to bytes
        pdf_bytes = pdf.output(dest='S').encode('latin-1')
        
        response = make_response(pdf_bytes)
        response.headers['Content-Type'] = 'application/pdf'
        response.headers['Content-Disposition'] = 'attachment; filename=simple_report.pdf'
        
        return response
    except Exception as e:
        return jsonify({'error': str(e)}), 500

# Method 3: Download existing PDF
@pdf_bp.route('/download-pdf/<filename>')
def download_pdf(filename):
    try:
        # Secure filename check
        safe_filename = os.path.basename(filename)
        pdf_path = os.path.join('static', 'pdfs', safe_filename)
        
        if os.path.exists(pdf_path):
            return send_file(pdf_path, as_attachment=True)
        else:
            return jsonify({'error': 'PDF not found'}), 404
    except Exception as e:
        return jsonify({'error': str(e)}), 500