from flask import Blueprint, request, jsonify, send_file
from flask_jwt_extended import jwt_required, get_jwt_identity
from app import db
from app.models import Will, User
from io import BytesIO
from fpdf import FPDF
import os

wills_bp = Blueprint('wills', __name__)


class WillPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'KENFUSE - End of Life Planning Platform', 0, 1, 'C')
        self.ln(5)
    
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')


def generate_will_pdf(will, user):
    """Generate a real PDF for a will"""
    from datetime import datetime
    
    pdf = WillPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Title
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, 'LAST WILL AND TESTAMENT', 0, 1, 'C')
    pdf.ln(5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(10)
    
    # Testator Information
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'TESTATOR INFORMATION', 0, 1)
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 8, f"Name: {user.first_name} {user.last_name}", 0, 1)
    pdf.cell(0, 8, f"Email: {user.email}", 0, 1)
    if user.phone:
        pdf.cell(0, 8, f"Phone: {user.phone}", 0, 1)
    pdf.ln(5)
    
    # Will Details
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'WILL DETAILS', 0, 1)
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 8, f"Title: {will.title}", 0, 1)
    pdf.cell(0, 8, f"Created: {will.created_at.strftime('%d %B, %Y')}", 0, 1)
    pdf.cell(0, 8, f"Status: {will.status.upper()}", 0, 1)
    pdf.cell(0, 8, f"Document ID: {str(will.id)[:8].upper()}", 0, 1)
    pdf.ln(10)
    
    # Declaration
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'DECLARATION', 0, 1)
    pdf.set_font('Arial', '', 11)
    declaration = (f"I, {user.first_name} {user.last_name}, being of sound mind and memory, "
                   f"do hereby make, publish, and declare this to be my Last Will and Testament, "
                   f"hereby revoking all former Wills and Codicils by me made.")
    pdf.multi_cell(0, 8, declaration)
    pdf.ln(10)
    
    # Will Content
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'WILL CONTENT', 0, 1)
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 8, will.content or 'No content provided.')
    pdf.ln(10)
    
    # Beneficiaries
    if will.beneficiaries:
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, 'BENEFICIARIES', 0, 1)
        pdf.set_font('Arial', '', 11)
        for beneficiary in will.beneficiaries:
            name = beneficiary.get('name', 'N/A')
            relationship = beneficiary.get('relationship', 'N/A')
            share = beneficiary.get('share', 'N/A')
            pdf.cell(0, 8, f"- {name} ({relationship}): {share}", 0, 1)
        pdf.ln(10)
    
    # Signatures
    pdf.add_page()
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'SIGNATURES', 0, 1)
    pdf.ln(10)
    
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 8, 'Testator:', 0, 1)
    pdf.cell(0, 15, '_' * 50, 0, 1)
    pdf.cell(0, 8, f"{user.first_name} {user.last_name}", 0, 1)
    pdf.cell(0, 8, f"Date: _______________", 0, 1)
    pdf.ln(15)
    
    pdf.cell(0, 8, 'Witness 1:', 0, 1)
    pdf.cell(0, 15, '_' * 50, 0, 1)
    pdf.cell(0, 8, 'Name: _________________________', 0, 1)
    pdf.cell(0, 8, 'ID: ___________________________', 0, 1)
    pdf.ln(15)
    
    pdf.cell(0, 8, 'Witness 2:', 0, 1)
    pdf.cell(0, 15, '_' * 50, 0, 1)
    pdf.cell(0, 8, 'Name: _________________________', 0, 1)
    pdf.cell(0, 8, 'ID: ___________________________', 0, 1)
    
    # Footer info
    pdf.set_y(-30)
    pdf.set_font('Arial', 'I', 8)
    pdf.cell(0, 5, f"Generated by KENFUSE on {datetime.utcnow().strftime('%Y-%m-%d %H:%M')}", 0, 1, 'C')
    pdf.cell(0, 5, f"Document ID: {will.id}", 0, 1, 'C')
    
    # Return PDF as bytes
    return pdf.output(dest='S').encode('latin-1')


@wills_bp.route('/', methods=['POST'])
@jwt_required()
def create_will():
    try:
        current_user_id = get_jwt_identity()
        user = User.query.get(current_user_id)
        
        if not user:
            return jsonify({'error': 'User not found'}), 404
        
        data = request.get_json()
        
        required_fields = ['title', 'content']
        for field in required_fields:
            if field not in data:
                return jsonify({'error': f'Missing field: {field}'}), 400
        
        # Create will
        will = Will(
            user_id=current_user_id,
            title=data['title'],
            content=data['content'],
            beneficiaries=data.get('beneficiaries', []),
            status=data.get('status', 'draft')
        )
        
        db.session.add(will)
        db.session.commit()
        
        return jsonify({
            'message': 'Will created successfully',
            'will': will.to_dict()
        }), 201
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@wills_bp.route('/', methods=['GET'])
@jwt_required()
def get_wills():
    try:
        current_user_id = get_jwt_identity()
        
        wills = Will.query.filter_by(user_id=current_user_id).all()
        
        return jsonify({
            'wills': [will.to_dict() for will in wills],
            'count': len(wills)
        }), 200
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@wills_bp.route('/<will_id>/pdf', methods=['GET'])
@jwt_required()
def export_will_pdf(will_id):
    try:
        current_user_id = get_jwt_identity()
        
        will = Will.query.filter_by(id=will_id, user_id=current_user_id).first()
        user = User.query.get(current_user_id)
        
        if not will or not user:
            return jsonify({'error': 'Will not found'}), 404
        
        # Generate real PDF
        pdf_content = generate_will_pdf(will, user)
        
        # Create BytesIO buffer
        buffer = BytesIO(pdf_content)
        buffer.seek(0)
        
        # Generate filename with .pdf extension
        filename = f"kenfuse_will_{will.title.replace(' ', '_')}.pdf"
        
        # Return as downloadable PDF
        return send_file(
            buffer,
            as_attachment=True,
            download_name=filename,
            mimetype='application/pdf'
        )
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@wills_bp.route('/test-pdf', methods=['GET'])
def test_pdf():
    """Test endpoint without authentication"""
    try:
        from datetime import datetime
        
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font('Arial', 'B', 16)
        pdf.cell(0, 10, 'KENFUSE TEST PDF', 0, 1, 'C')
        pdf.ln(10)
        pdf.set_font('Arial', '', 12)
        pdf.cell(0, 10, f'Generated: {datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")}', 0, 1)
        pdf.ln(5)
        pdf.multi_cell(0, 10, 'This is a test PDF document from KENFUSE.')
        
        pdf_content = pdf.output(dest='S').encode('latin-1')
        buffer = BytesIO(pdf_content)
        buffer.seek(0)
        
        return send_file(
            buffer,
            as_attachment=True,
            download_name="kenfuse_test.pdf",
            mimetype='application/pdf'
        )
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500