from flask import Blueprint, request, jsonify, send_file
from flask_jwt_extended import jwt_required, get_jwt_identity
from app import db
from app.models import Will, User
from io import BytesIO
import os

wills_bp = Blueprint('wills', __name__)

def generate_simple_pdf(will, user):
    """Generate a simple text PDF"""
    from datetime import datetime
    
    content = f"""
    KENFUSE - End of Life Planning Platform
    {'=' * 50}
    
    LAST WILL AND TESTAMENT
    {'=' * 50}
    
    Testator Information:
    Name: {user.first_name} {user.last_name}
    Email: {user.email}
    Phone: {user.phone}
    
    Will Details:
    Title: {will.title}
    Created: {will.created_at.strftime('%d %B, %Y')}
    Status: {will.status}
    Document ID: {will.id[:8].upper()}
    
    Declaration:
    I, {user.first_name} {user.last_name}, being of sound mind and memory,
    do hereby make, publish, and declare this to be my Last Will and Testament,
    hereby revoking all former Wills and Codicils by me made.
    
    Will Content:
    {will.content}
    """
    
    if will.beneficiaries:
        content += "\n\nBeneficiaries:\n"
        for beneficiary in will.beneficiaries:
            content += f"- {beneficiary.get('name', 'N/A')} ({beneficiary.get('relationship', 'N/A')}): {beneficiary.get('share', 'N/A')}\n"
    
    content += f"""
    
    {'=' * 50}
    Signatures
    
    Testator:
    _________________________
    {user.first_name} {user.last_name}
    Date: ___________________
    
    Witness 1:
    _________________________
    Signature: _____________
    ID: ____________________
    
    Witness 2:
    _________________________
    Signature: _____________
    ID: ____________________
    
    {'=' * 50}
    Generated by KENFUSE on {datetime.utcnow().strftime('%Y-%m-%d %H:%M')}
    Document ID: {will.id}
    """
    
    return content.encode('utf-8')

@wills_bp.route('/', methods=['POST'])
@jwt_required()
def create_will():
    try:
        current_user_id = get_jwt_identity()
        user = User.query.get(current_user_id)
        
        if not user:
            return jsonify({'error': 'User not found'}), 404
        
        data = request.get_json()
        
        required_fields = ['title', 'content']
        for field in required_fields:
            if field not in data:
                return jsonify({'error': f'Missing field: {field}'}), 400
        
        # Create will
        will = Will(
            user_id=current_user_id,
            title=data['title'],
            content=data['content'],
            beneficiaries=data.get('beneficiaries', []),
            status=data.get('status', 'draft')
        )
        
        db.session.add(will)
        db.session.commit()
        
        return jsonify({
            'message': 'Will created successfully',
            'will': will.to_dict()
        }), 201
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@wills_bp.route('/', methods=['GET'])
@jwt_required()
def get_wills():
    try:
        current_user_id = get_jwt_identity()
        
        wills = Will.query.filter_by(user_id=current_user_id).all()
        
        return jsonify({
            'wills': [will.to_dict() for will in wills],
            'count': len(wills)
        }), 200
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@wills_bp.route('/<will_id>/pdf', methods=['GET'])
@jwt_required()
def export_will_pdf(will_id):
    try:
        current_user_id = get_jwt_identity()
        
        will = Will.query.filter_by(id=will_id, user_id=current_user_id).first()
        user = User.query.get(current_user_id)
        
        if not will or not user:
            return jsonify({'error': 'Will not found'}), 404
        
        # Generate simple PDF
        pdf_content = generate_simple_pdf(will, user)
        
        # Create BytesIO buffer
        buffer = BytesIO(pdf_content)
        buffer.seek(0)
        
        # Generate filename
        filename = f"kenfuse_will_{will.title.replace(' ', '_')}.txt"
        
        # Return as downloadable file
        return send_file(
            buffer,
            as_attachment=True,
            download_name=filename,
            mimetype='text/plain'
        )
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@wills_bp.route('/test-pdf', methods=['GET'])
def test_pdf():
    """Test endpoint without authentication"""
    try:
        from datetime import datetime
        
        content = f"""
        KENFUSE TEST DOCUMENT
        {'=' * 50}
        
        This is a test PDF document.
        
        Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')}
        
        Features:
        - Will management
        - Memorial creation
        - Fundraising
        - Vendor marketplace
        
        {'=' * 50}
        End of test document
        """
        
        buffer = BytesIO(content.encode('utf-8'))
        buffer.seek(0)
        
        return send_file(
            buffer,
            as_attachment=True,
            download_name="kenfuse_test_document.txt",
            mimetype='text/plain'
        )
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500

# Other routes remain the same...
